# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 03:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('opening_content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Teaser text to appear on main blog page')),
                ('extended_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Remainder of text to appear on detail page of entry (optional)', null=True)),
                ('published', models.IntegerField(choices=[(1, 'Published'), (2, 'Draft')], default=2, help_text="Set to 'Published' when post is ready to appear to public")),
                ('publish_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
