# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 20, 1, 41, 16, 294974, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
