# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 12:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160520_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='extended_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='opening_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
