# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 5, 14, 16, 35, 55, 736283, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'Draft')]),
        ),
    ]
