# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20160514_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'Draft')], default=2),
        ),
    ]
